JOINT_NAMES = (
    "JOINT_HIP_PITCH_L",
    "JOINT_HIP_ROLL_L",
    "JOINT_HIP_YAW_L",
    "JOINT_KNEE_PITCH_L",
    "JOINT_ANKLE_PITCH_L",
    "JOINT_ANKLE_ROLL_L",
    "JOINT_HIP_PITCH_R",
    "JOINT_HIP_ROLL_R",
    "JOINT_HIP_YAW_R",
    "JOINT_KNEE_PITCH_R",
    "JOINT_ANKLE_PITCH_R",
    "JOINT_ANKLE_ROLL_R",
    "joint_wy",
    "joint_hy",
    "joint_la1",
    "joint_la2",
    "joint_la3",
    "joint_la4",
    "joint_la5",
    "joint_ra1",
    "joint_ra2",
    "joint_ra3",
    "joint_ra4",
    "joint_ra5",
)

MOTION_BODY_NAMES = (
    "pelvis",
    "LINK_HIP_PITCH_L",
    "LINK_HIP_ROLL_L",
    "LINK_HIP_YAW_L",
    "LINK_KNEE_PITCH_L",
    "LINK_ANKLE_PITCH_L",
    "LINK_ANKLE_ROLL_L",
    "LINK_FOOT_L",
    "LINK_TOE_L",
    "LINK_HIP_PITCH_R",
    "LINK_HIP_ROLL_R",
    "LINK_HIP_YAW_R",
    "LINK_KNEE_PITCH_R",
    "LINK_ANKLE_PITCH_R",
    "LINK_ANKLE_ROLL_R",
    "LINK_FOOT_R",
    "LINK_TOE_R",
    "link_wy",
    "link_hy",
    "link_la1",
    "link_la2",
    "link_la3",
    "link_la4",
    "link_la5",
    "LINK_HAND_L",
    "link_ra1",
    "link_ra2",
    "link_ra3",
    "link_ra4",
    "link_ra5",
    "LINK_HAND_R",
    "imu_link_at_pelvis",
)

AMP_BODY_NAMES = (
    "pelvis",
    "LINK_HIP_PITCH_L",
    "LINK_KNEE_PITCH_L",
    "LINK_ANKLE_ROLL_L",
    "LINK_HIP_PITCH_R",
    "LINK_KNEE_PITCH_R",
    "LINK_ANKLE_ROLL_R",
    "link_la1",
    "link_la4",
    "link_la5",
    "link_ra1",
    "link_ra4",
    "link_ra5",
)

AMP_ANCHOR_NAME = "link_wy"
ROOT_BODY_NAME = "pelvis"
FEET_BODY_NAMES = ("LINK_ANKLE_ROLL_L", "LINK_ANKLE_ROLL_R")
FEET_SITE_NAMES = ("l_foot_center", "r_foot_center")
FEET_GEOM_NAMES = ("l_foot", "r_foot")

DEFAULT_STANDING_JOINT_POS = {
    "JOINT_HIP_PITCH_L": -0.20,
    "JOINT_HIP_ROLL_L": -0.02,
    "JOINT_HIP_YAW_L": 0.00,
    "JOINT_KNEE_PITCH_L": 0.40,
    "JOINT_ANKLE_PITCH_L": -0.22,
    "JOINT_ANKLE_ROLL_L": 0.00,
    "JOINT_HIP_PITCH_R": -0.20,
    "JOINT_HIP_ROLL_R": -0.02,
    "JOINT_HIP_YAW_R": 0.00,
    "JOINT_KNEE_PITCH_R": 0.40,
    "JOINT_ANKLE_PITCH_R": -0.22,
    "JOINT_ANKLE_ROLL_R": 0.00,
    "joint_wy": 0.00,
    "joint_hy": 0.00,
    "joint_la1": 0.25,
    "joint_la2": 0.10,
    "joint_la3": 0.00,
    "joint_la4": 0.45,
    "joint_la5": 0.00,
    "joint_ra1": 0.20,
    "joint_ra2": -0.10,
    "joint_ra3": 0.00,
    "joint_ra4": 0.65,
    "joint_ra5": 0.00,
}
